### ISSUE TITLE
debugging messages when adding a card

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#14]
Notice: Constant  already defined in /www/moodle/mod/cardbox/controller.php on line 27

Notice: Constant SHORT_DESCRIPTION already defined in /www/moodle/mod/cardbox/controller.php on line 28

Notice: Undefined property: stdClass::$disableautocorrect in /www/moodle/mod/cardbox/controller.php on line 118

looks like they are defined in both locallib and controller files

also - those names are not correct either - contants should be prefixed with the plugin name "cardbox"

**Comment by Amrita1991** [comment]
solved with [this](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/663faa0730680e39886febe1aa40069806149f8a)
