### ISSUE TITLE
debugging messages on overview page

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#15]
Notice: Undefined index: ismob www/moodle/mod/cardbox/controller.php on line 980

Notice: Undefined index: ismob in www/moodle/mod/cardbox/controller.php on line 985

Notice: Undefined property: cardbox_card::$repsnummer in www/moodle/mod/cardbox/classes/output/card.php on line 254

Notice: Undefined property: cardbox_card::$acimgurl in www/moodle/mod/cardbox/classes/output/card.php on line 256

**Comment by Amrita1991** [comment]
solved with [this](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/663faa0730680e39886febe1aa40069806149f8a)
