### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#2]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin stores user data in a number of tables which will need to be included in the privaci api classes.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API'

note - this is not typically a blocker for plugins db approval

**Comment by Amrita1991** [comment]
Privacy API implemented with commits [e2b6d33f24850ddfe51484dfee611787be4cfa8d](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/e2b6d33f24850ddfe51484dfee611787be4cfa8d) and [5649c992d33844cf881d90ab8daf6185b08ffd2b](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/5649c992d33844cf881d90ab8daf6185b08ffd2b)
