### ISSUE TITLE
Feature Request: Display other-than-text answers (Videos, GIF...)

### ISSUE THREAD

**Issue by 123dennis** [rwthmoodle/moodle-mod_cardbox#20]
EDIT:

The problem seems to be this:
- I defined the cards with an image/video on the answer side as “Self-Check Only”. I also have cards who have text on the answer side (with “Auto-Check” enabled).
- When I click on “Practice” and choose the practice mode “Automatic Check”, the answer sides of cards with text answers are displayed correctly, but answer sides with image/video (and “Self-Check Only”) are not displayed.
- But when I select the practice mode “Check yourself”, all answers (both text answers and image/video answers) are shown correctly.
- So the question would be: Is it possible to have Automatic Check answers and Self-Check only answers in the same practice run?
----
Original post:

Hello,
currently, I can display multimedia (JPG, MP4, GIF…) on the question side of the card, and the solution is text-only. During the “Practice” mode of the Cardbox, any multimedia I add to the answer side of the card is not displayed. Is there a way to also add multimedia support to the answer side of the card? It would be great to productively learn visual information (such as signs). Attached is the current variant (A) and the proposed new variant (B).

Best regards!

![Github Request](https://user-images.githubusercontent.com/112392208/187189460-34197dff-e6b9-4013-a95e-034cb5b12aee.jpg)

**Comment by Amrita1991** [comment]
Hello @123dennis
We have an option option called 'Disable Automatic Check' in the 'Add card' tab. Enabling this option, will make the card appear in Self Check mode even when it is in Automatic Check mode. We included this feature to allow students to check themselves when a card has a complicated answer. I think this feature would be useful. As of now, for answers we only show texts in both practice modes. But with future release we can display multimedia aspects of answers for 'Self Check only' cards

**Comment by 123dennis** [comment]
Hello @Amrita1991 
Thanks for your reply and for clarifying the Cardbox functions to me. I found that using the "Check yourself" mode, multimedia answers are already shown, which is ideal for my purposes. It would also be a useful addition if you could enable multimedia answers in the "Automatic Check" mode in a future release.
