### ISSUE TITLE
Bug: parsing error in controller.php

### ISSUE THREAD

**Issue by grabs** [rwthmoodle/moodle-mod_cardbox#22]
Hi,
in **controller.php** in **line 476** after `CARD_MAIN_INFORMATION` is a comma which shouldn't be there.
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/controller.php#L476
It would be nice if you could fix this.
Thank you very much for this great plugin!

**Comment by Amrita1991** [comment]
This issue has been corrected with the new release [v1.0.3](https://github.com/rwthmoodle/moodle-mod_cardbox/tree/v1.0.3).
