### ISSUE TITLE
missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#3]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

I didn't look at all your JS - but I noticed chart.js in there... Moodle already includes chart.js in the core release, so unless there's a reason you need a different version than what core provides it would be better to leverage the one in core.

**Comment by Amrita1991** [comment]
I removed the Chartbundle.js and now the code calls the chart.js included in Moodle core.
The changes are visible in this [commit](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/dd4bba891d9e4c4d59d53339286bd8005036fa67). Can you please verify if this is ok.

**Comment by danmarsden** [comment]
if you don't have any other 3rd party code you're distributing in your plugin that sounds perfect to me! :-)
