### ISSUE TITLE
only closing html tag in help string

### ISSUE THREAD

**Issue by koenr** [rwthmoodle/moodle-mod_cardbox#30]
The string  help:nocardsavailableforpractice_help | cardbox  contains a `</ul> `only at the end.
The closing tag shouldn't be there.
The use of HTML in strings should be avoided according to documentation on https://docs.moodle.org/dev/String_API#Help_strings

**Comment by Amrita1991** [comment]
Thanks for bringing this to my attention. I understand I have to look into the help for no cards available for practice since there is another issue (#31) as well. Hpefully we can correct this with the new release
