### ISSUE TITLE
Improvement: firstsname in email, not username

### ISSUE THREAD

**Issue by koenr** [rwthmoodle/moodle-mod_cardbox#33]
The string remindergreeting | cardbox  gives the username in the e-mail notificaiton, e.g.

Beste 1600087,

denk er aan om regelmatig met je kaartendoos te studeren.

Firstname would be nicer I think.

**Comment by maodoanminnh** [comment]
I agree.

**Comment by Amrita1991** [comment]
Thanks for reporting this. We have taken this in our Backlog

**Comment by Amrita1991** [comment]
This issue has been corrected with the new release [v1.0.3](https://github.com/rwthmoodle/moodle-mod_cardbox/tree/v1.0.3).
