### ISSUE TITLE
improvement: make notifications configurable

### ISSUE THREAD

**Issue by koenr** [rwthmoodle/moodle-mod_cardbox#34]
We are testing the module extensively and found that it sends a lot of messages, some of them not correct.

- invite to practice e-mail from a hidden card box. This is confusing to students since it is not available to them yet.
- notification on card change - also for new cards no one has ever seen during development of a new card box activity. 
I think sending messages should be something a teacher can enable at the activity-level if appropriate, but off by default.

**Comment by koenr** [comment]
Students unfortunately get so many reminders that they become useless.
Until there is a finer mechanism to tweak the messages, I disabled \mod_cardbox\task\remind in the task manager.

**Comment by Amrita1991** [comment]
Thanks for reporting this. We have taken this in our backlog

**Comment by Amrita1991** [comment]
This issue has been corrected with the new release [v1.0.3](https://github.com/rwthmoodle/moodle-mod_cardbox/tree/v1.0.3).
