### ISSUE TITLE
Card jumps right to Deck 2 after one learning cycle

### ISSUE THREAD

**Issue by 123dennis** [rwthmoodle/moodle-mod_cardbox#35]
I noticed that all cards jump from Deck "New" to Deck "2" after one learning cycle. Should they not go to Deck "1" instead?
Best regards!

![Cardbox Progress](https://user-images.githubusercontent.com/112392208/194551044-1d5a3510-32f6-4c43-b311-3a270c18cabe.png)

**Comment by maodoanminnh** [comment]
I think this is understandable. What I saw is that for a new card, if the learner can remember the term the first, second, or third time seeing it, it will go to deck 2. If they struggle more, it'll go to deck 1.

**Comment by 123dennis** [comment]
Hello, thanks for your input! I tested it with a few cards, and I found that with a new card, if the learner clicks on "Incorrect" once, it goes to deck 1. Which means, as you say, new cards the learner answers correctly on the first try go to Deck 2.

![Cardbox Progress 18 10 2022](https://user-images.githubusercontent.com/112392208/196376986-33b6b1cf-f0f3-454c-af34-d9f4cb4d324c.png)

**Comment by Amrita1991** [comment]
Thanks @koenr and @maodoanminnh for the clarification. Yes it is intentional behaviour the new cards answered correctly will go to deck 2 and new cards that has been once incorrectly answered will move to Deck 1.With that, I will close this issue now since it has been clarified
