### ISSUE TITLE
Improvement: A teacher should decide whether emails should be sent or not

### ISSUE THREAD

**Issue by Dmfama20** [rwthmoodle/moodle-mod_cardbox#38]
Hi,
unfortunately the weekly e-mail reminder of mod_carbox can't be modified by teachers, i.e. each student receives a reminder in order to use the module frequently. This could be to annoying for students, depending on the significance of the single activity.

Maybe you could add a checkbox in the activity configuration, where the teacher can enable/disable e-mail notification, when the activity is created. Additionally, you could add a checkbox in "site administration->configuration of mod_cardbox" where admins can configure the default value of the checkbox (mentioned above) in activity configuration.
TIA!
Alex

**Comment by Amrita1991** [comment]
This has been already reported in #34 hence I am closing this issue. We are currently working on moodle 4.0 issues therefore have not been able to update the cardbox plugin but will get to it soon.
