### ISSUE TITLE
In "Overview", clicking through Topic-filtered pages resets the filter

### ISSUE THREAD

**Issue by 123dennis** [rwthmoodle/moodle-mod_cardbox#42]
When I go to the “Overview” and filter by topic, such as “Berufe”, and there are more cards than can be displayed on one page, the filter resets, and it shows me page 2 of the unfiltered list.

Example:

![Filter Reset after Filter and Click on Page 2](https://user-images.githubusercontent.com/112392208/221591574-243ce95d-577e-4a8a-8b11-bb5bb2259084.png)

**Comment by Amrita1991** [comment]
Thanks for reporting this issue. We are currently running late with our next release due to Moodle 4 upgrade at our end but we hope to include this in the next release soon
