### ISSUE TITLE
Bug with 'I don't know' after correct answer

### ISSUE THREAD

**Issue by jamesstanforth** [rwthmoodle/moodle-mod_cardbox#43]
The 'I don't know' button correctly displays the answers until the user has got one right and gets 'Well done!'. Following this, clicking on 'I don't know' gives 'Well done!' instead of the correct answers... see here: https://drive.google.com/file/d/1kxKXZ9f1rTKJZImQ4UFIEIKtH4sd01b3/view?usp=sharing

**Comment by Amrita1991** [comment]
I tested this situation and couldnt recreate it. As before if this problem persists, please send us a backup of your activity(where this problem is occurring) so that we can analyse

**Comment by jamesstanforth** [comment]
Thanks, @Amrita1991 - I've just tested again with the attached and the same problem occurs for me. After one (or sometimes two) correct answers, when I click 'I don't know' it still says 'Well done!' rather than the correct answers. I've also found that when I upload the attached even though 'Default settings for "How many answers are necessary?"' is set to 'one', it defaults all imported cards to 'All' meaning they have to be edited individually?

[Latin Vocab.csv](https://github.com/rwthmoodle/moodle-mod_cardbox/files/11237257/Latin.Vocab.csv)

**Comment by jamesstanforth** [comment]
@Amrita1991 - just following up on this to see if the bug can be fixed? The issue occurs with multeans where the 'How many answers are necessary?' setting to 'one'. Then, when you get one of these correct and then click 'I don't know' on the next card, it says 'Well done!'. This doesn't happen if ALL answers are required for the multean.

**Comment by koenr** [comment]
I had a teacher reporting the same problem, so I can confirm this bug.
