### ISSUE TITLE
Bug: text box too small for second sollution with TinyMCE

### ISSUE THREAD

**Issue by koenr** [rwthmoodle/moodle-mod_cardbox#47]
When adding a second solution for a card, using the now default TinyMCE editor, the box is too small to type in.

![Schermafdruk van 2023-09-18 08-35-23](https://github.com/rwthmoodle/moodle-mod_cardbox/assets/2964998/b8fdde21-a193-403c-978c-52dedf676b83)

**Comment by Amrita1991** [comment]
thank you for reporting this. We have taken the issue in our Backlog and will try to resolve it soon

**Comment by Amrita1991** [comment]
hello @koenr is this problem still occuring? if yes can you please tell me which version of Moodle you are using?

**Comment by koenr** [comment]
Hello Amrita,
Thank you for comming back to this.
It seems to be solved in the Moodleversion we have in use at the moment: Moodle 4.3.3+ (Build: 20240215) as you can see in the screenshot.

I'm about to upgrade to Moodle's latest. - I'll keep it in mind to retest, but it will probably be fine.

![Schermafdruk van 2024-08-13 16-00-50](https://github.com/user-attachments/assets/a8833073-5ada-433a-8fb0-cd51dc003bc2)
