### ISSUE TITLE
Bug: coding error when practicing with sysadmin account

### ISSUE THREAD

**Issue by koenr** [rwthmoodle/moodle-mod_cardbox#48]
When clicking "Practice" as a system administrator, a coding error is thrown:

Fout in de programmeercode gevonden. Dit moet door een programmeur hersteld worden. Attempt to require a JavaScript file that does not exist.

Meer informatie over deze fout
Foutopsporingsinformatie:  /mod/cardbox/js/Chart.bundle.js
Error code: codingerror
Stack trace: 

    line 736 of /lib/outputrequirementslib.php: coding_exception thrown
    line 722 of /lib/outputrequirementslib.php: call to page_requirements_manager->js_fix_url()
    line 451 of /lib/outputrequirementslib.php: call to page_requirements_manager->js_fix_url()
    line 657 of /mod/cardbox/controller.php: call to page_requirements_manager->js()
    line 61 of /mod/cardbox/view.php: call to require_once()

**Comment by Amrita1991** [comment]
thank you for reporting this. We have taken the issue in our Backlog and will try to resolve it soon

**Comment by koenr** [comment]
This is solved
