### ISSUE TITLE
has this been tested in postgres?

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#5]
some of your group by statements look to me like they might not work in postgres - can you please make sure you test this in a postgres install? - Postgres and mysql/mariadb must be supported by plugins in the plugins db.

**Comment by Amrita1991** [comment]
Hi. 
We have only tested this in MySQL. Currently the postgres hosting servers of our organisation is under repair so we couldn't complete it. If this is a blocker, I will push the team to make it available

**Comment by danmarsden** [comment]
postgres support is definitely required for plugins db approval and as I'm a volunteer, I'd prefer not to be the first person to try it on postgres myself :-)

**Comment by Amrita1991** [comment]
tested with Postgres. removed inconsistencies found with this [commit](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/3affa0d4946d617cc1a2b60d54f43a85b9878510)

**Comment by danmarsden** [comment]
cool! - those are the queries I spotted that looked like they might not work in postgres - nice work! :-)
