### ISSUE TITLE
PHP error for "CARD_ANSWERSUGGESTION_INFORMATION" in the review tab

### ISSUE THREAD

**Issue by T1mL1d3r** [rwthmoodle/moodle-mod_cardbox#51]
Dear developers,

Thank you for this very useful plugin. I use it weekly with my students in highschool.

Since the June 2023 update (from 1.0.2 to 1.0.3) there is a bug when I open the Review tab.
The bug is : PHP error for "CARD_ANSWERSUGGESTION_INFORMATION". I don't remember exactly the sentence as I "debuged" the system some weeks ago and now I updated to 1.0.4 and I could see in the source code file that the problem seems to still be there.

To resolve this issue I had to replace in actions.php, locallib.php and reviewform.php the value "CARD_ANSERSUGGESTION_INFORMATION" by the value "CARD_ANSWERSUGGESTION_INFORMATION". See the missing W in the original code.

I did it again in the source code file for the 1.0.4 and it works great.

I use an up to date moodle 4.2 with the last PHP version.

I hope this solution can be implemented in the next update and that it can be useful for others.

Thank you again for developing and sharing this plugin.

**Comment by koenr** [comment]
I can confirm this problem and the fix works indeed. Thank you

These are all the affected lines and their fix:
```
action.php:                                     $userinput, CARD_ANSWERSUGGESTION_INFORMATION);
controller.php:            array_merge(['area' => CARD_ANSWERSUGGESTION_INFORMATION, 'cardside' => CARDBOX_CARDSIDE_ANSWER], $inparams));
locallib.php:define('CARD_ANSWERSUGGESTION_INFORMATION', 3);
locallib.php:        'area' => CARD_ANSWERSUGGESTION_INFORMATION]);
review_form.php:                    'areasugg' => CARD_ANSWERSUGGESTION_INFORMATION
review_form.php:                        ['cardside' => CARDBOX_CARDSIDE_ANSWER, 'card' => $cardid, 'area' => CARD_ANSWERSUGGESTION_INFORMATION]);
review_form.php:                        $answerapproved = $cardcontent->area != CARD_ANSWERSUGGESTION_INFORMATION;
review_form.php:                            'cardside' => CARDBOX_CARDSIDE_ANSWER, 'area' => CARD_ANSWERSUGGESTION_INFORMATION], '', 'id, content');

```

**Comment by t-schroeder** [comment]
Thanks for the hint and sorry for the oversight. I've released a new version containing this fix.

**Comment by T1mL1d3r** [comment]
Thank you very much.
