### ISSUE TITLE
BUG: Equations in Answer text not displayed correctly

### ISSUE THREAD

**Issue by bkasel** [rwthmoodle/moodle-mod_cardbox#55]
Hi I am using cardbox 1.0.3 on Moodle 4.4. 

Equations in the answer text are not being rendered through mathjax when in practice mode (equations in the prompt are displayed correctly at the same time), while in th overview pane, all equations render correctly.

**Comment by bkasel** [comment]
It seems I fixed the issue by inverting the logic for trimming html tags etc for on [these lines](https://github.com/rwthmoodle/moodle-mod_cardbox/blob/fe78dd1c30e3b3f668d0497c44099a25b98f4be9/classes/output/practice.php#L166C1-L171C18)

I believe it should be `if (!$disableautocomplete)` so that formulae may be displayed correctly when no autocorrect is needed.

**Comment by Amrita1991** [comment]
Thank you for reporting and suggesting solutions. We haven't yet checked the plugin's compatibility with Moodle 4.4 since we are currently at 4.3.5. We need to check first which versions have this problem and then test out your solution. Please bear with us as we work on this.

**Comment by bkasel** [comment]
thanks for the response. I think it it is a logical problem not related to versions.
if `$disableautocorrect` is true you *don't* want to trim tags, which is what the code does.

**Comment by Amrita1991** [comment]
I tried implementing your solution however when answer contains just text and no equations and the student gives the right answer, it is evaluated as wrong. Did you face this?

**Comment by bkasel** [comment]
I was not using auto-correct, but you are right, the `<p>` tags are not being removed if you want the user to type in the correct answer, but that points to the fact there is another issue. Somehow the if clause does not get executed if auto correct is not disabled (i.e. enabled)

![grafik](https://github.com/rwthmoodle/moodle-mod_cardbox/assets/16179803/c428f99a-0777-4c7d-91ba-c58b34594c4c)

**Comment by bkasel** [comment]
is `$disableautocorrect` always set to false if you want auto correction for the user?

**Comment by Amrita1991** [comment]
we didnt have equations as answers in mind when we conceptualised the plugin. The plugin serves purely text based answers. Hence all kinds of attached HTML are always removed with `$disableautocorrect`
If we are to allow equation based answers we have 2 ways:

- prompt the student to enclose their answers within` \(...\) `using the context field to provide hint 
- we add a flag that the card creator has to check to denote that answer is an equation so the code will treat it in a special way

From our side since we had fundamentally decided to build this plugin for purely text based answers, I am not sure if this will be something we will work on(atleast nopt in priority).
However do let us know which approach sounds good to you and you/anyone else is welcome to develop on this and create a pull request

**Comment by Amrita1991** [comment]
> is `$disableautocorrect` always set to false if you want auto correction for the user?

If the user is practising in automatic check this gets set to true so that the HTML tags get stripped from the answer and we can compare better

**Comment by Nukker1** [comment]
In the Cardbox settings, you can globally enable or disable autocorrection. Autocorrection is only suitable for short text entries, not for formula answers and mathematical equations, as there are many correct ways of writing them that cannot all be considered. Similar tools like Dialog Cards in H5P also face this issue.
If you want to use both flashcards with and without autocorrection in one single Cardbox activity, you can enable global autocorrection in the Cardbox settings. For new flashcards that don't require autocorrection (e.g., mathematical equations or formulas), you can select the "Disable Automatic Check" option when adding a card. This way, autocorrection will not be applied to cards with mathematical questions or formulas

**Comment by Amrita1991** [comment]
Since this is more a problem due to false setup, I am closing the ticket.

**Comment by bkasel** [comment]
Hello @Amrita1991 ,

Sorry for bugging you more with this. I still believe there is a problem.

I would like to have both cards with Auto-correct and without autocorrect in a single activity. For example, I put two cards in this csv file for you to test.

[test_cards.csv](https://github.com/user-attachments/files/16365272/test_cards.csv)

In the settings of the activity I set,
![grafik](https://github.com/user-attachments/assets/0d2d2bac-ee06-48ca-8fb0-7a4094eb4bfd)
 because I need autocorrection for one of the cards. If I practice this with the original code, the formula does not get displayed correctly (tags get stripped)  but I can automatically check the correct answer for the second  card. 

If I unselect
![grafik](https://github.com/user-attachments/assets/b60a2325-5182-4570-8e46-54f329d01fb4)
the formula gets displayed correctly (no tags stripped), but I can no longer automatically check the second question.

I would expect the first case to display the equation correctly.

So I do believe that this line https://github.com/rwthmoodle/moodle-mod_cardbox/blob/fe78dd1c30e3b3f668d0497c44099a25b98f4be9/classes/output/practice.php#L166
needs to be adapted, so that if a question has automatic check disabled:
![grafik](https://github.com/user-attachments/assets/2befb4ce-402f-4c6e-9e59-2109f0baf843)
the tags don't get stripped

**Comment by Amrita1991** [comment]
ok I can recreate the problem with your csv so we will look into this again. Hence reopening the ticket

**Comment by Amrita1991** [comment]
We have corrected this with recent update. Please check and let us know if the solution resolves your problems

**Comment by bkasel** [comment]
I deployed the main branch of your repo on my moodle site. The problem has been solved!
Thank you 👍
