### ISSUE TITLE
Conflict with Moodle 4.5: message_email

### ISSUE THREAD

**Issue by mattgig** [rwthmoodle/moodle-mod_cardbox#59]
When upgrading a Moodle system from 4.4 to 4.5 the cardbox plugin throws an error during the installation process:

```
message_email
Exception - Undefined constant "MESSAGE_DEFAULT_LOGGEDIN"

More information about this error

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 34 of /mod/cardbox/db/messages.php: Error thrown
line 692 of /lib/messagelib.php: call to require()
line 487 of /lib/messagelib.php: call to message_get_providers_from_file()
line 629 of /lib/upgradelib.php: call to message_update_processors()
line 771 of /lib/upgradelib.php: call to upgrade_component_updated()
line 1937 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()
```

**Comment by Amrita1991** [comment]
Does this error completely prohibits cardbox installation or is it more like a warning that can be worked around? 
We have 4.5 compatibility check planned next month. Hence I am asking in case we have to prioritise this

**Comment by mattgig** [comment]
I tried again, deinstalled and reinstalled the plugin again. The installation went through without an error. My guess is that the error really only occurs when you upgrade. However, I unfortunatelly can't tell whether the error can be skipped by clicking on the continue button, as I made sume adjustments in the db/messages.php file. (Your plugin was not the only one to throw such an error, there are several reports from other plugins and other instances.) Sorry, for not being of more help.

**Comment by Amrita1991** [comment]
That's ok @mattgig . I will keep this issue open for a week or so if anyone else experience something similar, they can report it here. Btw, did you have the plugin's latest version when you were upgrading?

**Comment by mattgig** [comment]
I had the lastest version for Moodle 4.4 installed.

**Comment by t-schroeder** [comment]
Hi, that constant has been removed in release 1.0.3 of mod_cardbox already. Did you perhaps try to upgrade Moodle core before mod_cardbox? How did you perform the upgrade exactly?

**Comment by mattgig** [comment]
For major upgrades, I delete the Moodle core folder and install it with the new vesion, afterwards I copy the old plugin directories over to the new installation. So at the time of the upgrade, the old version was present. I only upgrade the plugins, when I get the notification that a newer version is present.

**Comment by Amrita1991** [comment]
we have tried this but it doesn't come up as an error in 4.5 or 5.0 installation. Perhaps you had a really old version and so when you upgraded without changing the plugin, you face dthe problem. I am closing this issue since none else has reported encountering such a problem
