### ISSUE TITLE
action.php appears to miss capability checks

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#6]
the action.php file seems to check if the user is logged in and enrolled in the course, but I suspect actions like approve/reject should be wrapped in a has_capability check against mod/cardbox:approvecard  or some of your other capabilites.

You should check to make sure the user has the capability required for each action.

**Comment by danmarsden** [comment]
for example - I see a capability check when someone cancels the form, but I don't actually see a capability check occurring when they post data to the form.

**Comment by Amrita1991** [comment]
I checked and tested the code. The function for action ===review part of action.php, which  you mention, was no longer getting called and irrelevant. I guess we just forgot to remove this. I have done so now in this [commit](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/9a07d54d382bb16f77e35f87974facd5096b28f5)
