### ISSUE TITLE
function naming violation

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#7]
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/locallib.php#L740
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/locallib.php#L794
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/locallib.php#L813

Functions must use the frankenstyle naming convention:
https://docs.moodle.org/dev/Frankenstyle#Function_names

note this is a blocker for plugins db approval.

**Comment by Amrita1991** [comment]
this is fixed in this [comment](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/1fe55a100ab18981f8a290b0b47df5f2633c818a)
