### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#8]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 
eg:
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/styles.css#L10-L29
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/styles.css#L220-L222
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/styles.css#L583-L587

Those are just examples - there are probably others that need fixing too.

Moodle collects all the styles.css files from plugins and bundles them into a single css file for passing to the users browser - this means that all your styles must be really specific to avoid modifying the display of other areas inside moodle.

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by Amrita1991** [comment]
I fixed these with this [commit](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/9a07d54d382bb16f77e35f87974facd5096b28f5)
