### ISSUE TITLE
hard-coded english string

### ISSUE THREAD

**Issue by danmarsden** [rwthmoodle/moodle-mod_cardbox#9]
https://github.com/rwthmoodle/moodle-mod_cardbox/blob/main/view.php#L41'

note this is a blocker for plugins db approval.

**Comment by Amrita1991** [comment]
this is solved in [this commit](https://github.com/rwthmoodle/moodle-mod_cardbox/commit/1fe55a100ab18981f8a290b0b47df5f2633c818a)
